# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='item',
        ),
        migrations.AddField(
            model_name='quantity',
            name='order_items',
            field=models.ManyToManyField(to='app.MenuItem'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(to='app.Quantity'),
        ),
    ]
